"""added created_at columns to tables

Revision ID: 0b93ff584aff
Revises: 
Create Date: 2022-02-17 10:50:05.798811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b93ff584aff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('attribute_set', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('car_categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('car_models', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('data_types', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('entity_type', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('group_entity', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('monthly_payment_types', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('order_sales_group', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('product_categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('stock', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('stock_history_group', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_history_group', 'created_at')
    op.drop_column('stock', 'created_at')
    op.drop_column('product_categories', 'created_at')
    op.drop_column('order_sales_group', 'created_at')
    op.drop_column('monthly_payment_types', 'created_at')
    op.drop_column('group_entity', 'created_at')
    op.drop_column('entity_type', 'created_at')
    op.drop_column('employees', 'created_at')
    op.drop_column('data_types', 'created_at')
    op.drop_column('car_models', 'created_at')
    op.drop_column('car_categories', 'created_at')
    op.drop_column('attribute_set', 'created_at')
    op.drop_column('attribute', 'created_at')
    # ### end Alembic commands ###
